// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4V8Kj9YTY1tP_jDPcCt1Xv3gAYCz4xUU',
    appId: '1:418699789350:android:12f4b1d40c7bb82475d2e7',
    messagingSenderId: '418699789350',
    projectId: 'ccu-prototype',
    storageBucket: 'ccu-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVBv7-iitsUm9-fzfmU5vMbIvhVq2FZ4',
    appId: '1:418699789350:ios:215d9e7035a0f04675d2e7',
    messagingSenderId: '418699789350',
    projectId: 'ccu-prototype',
    storageBucket: 'ccu-prototype.appspot.com',
    iosClientId: '418699789350-vkoc793uulbrs2spcl720fq88qh5h96g.apps.googleusercontent.com',
    iosBundleId: 'com.ccu.app',
  );
}
